Import('env')

# python extension module
module = env.SharedLibrary('srreal_ext', Glob('*.cpp'), SHLIBPREFIX='')
Alias('module', module)

# install in a development mode
Alias('develop', Install('#/diffpy/srreal', module))

# default targets:
Default(module)

# vim: ft=python
