[build-system]
requires = [
    "scikit-build-core>=0.10",
    "setuptools-scm>=8",
    "numpy",
    "nanobind>=2.13,<4",
]
build-backend = "scikit_build_core.build"

[project]
name = "diffpy.srreal"
dynamic = ["version"]
dependencies = ["numpy"]
authors = [
  { name="Simon Billinge", email="sb2896@columbia.edu" },
]
maintainers = [
  { name="Simon Billinge", email="sb2896@columbia.edu" },
]
description = "Calculators for PDF, bond valence sum, and other quantities based on atom pair interaction."
keywords = ['PDF', 'BVS', 'atom', 'overlap', 'calculator', 'real-space']
readme = "README.rst"
requires-python = ">=3.12, <3.15"
classifiers = [
        'Development Status :: 5 - Production/Stable',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX',
        'Operating System :: Unix',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Python :: 3.14',
        'Topic :: Scientific/Engineering :: Physics',
        'Topic :: Scientific/Engineering :: Chemistry',
]

[project.urls]
Homepage = "https://github.com/diffpy/diffpy.srreal/"
Issues = "https://github.com/diffpy/diffpy.srreal/issues/"

[tool.scikit-build]
minimum-version = "build-system.requires"
cmake.build-type = "Release"
wheel.packages = ["src/diffpy"]
sdist.exclude = [".agents", ".codex", "cache", "build", "dist"]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"

[project.optional-dependencies]
test = ["pytest", "diffpy.structure", "periodictable"]

[tool.codespell]
exclude-file = ".codespell/ignore_lines.txt"
ignore-words = ".codespell/ignore_words.txt"
skip = "*.cif,*.dat"

[tool.docformatter]
recursive = true
wrap-summaries = 72
wrap-descriptions = 72

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.rst
  | \.txt
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''
