Environment().EnsureSConsVersion(0, 98)
import os.path

# Customizable compile variables
vars = Variables('sconsvars.py')

vars.Add('tests', 'Custom list of unit test sources', 'all')
vars.Add(EnumVariable('build',
    'compiler settings', 'debug',
    allowed_values=('debug', 'fast')))
vars.Add(PathVariable('prefix',
    'installation prefix directory', '/usr/local'))
vars.Add(PathVariable('libdir',
    'object code library directory [prefix/lib]', None))
vars.Add(PathVariable('includedir',
    'installation directory for C++ header files [prefix/include]', None))

# Default build environment
env = DefaultEnvironment(variables=vars)
Help(vars.GenerateHelpText(env))

env.ParseConfig("python-config --includes")
env.ParseConfig("python-config --ldflags")
env.ParseConfig("gsl-config --cflags --libs")

if env['build'] == 'debug':
   env.Append(CCFLAGS='-g')
env.Append(CCFLAGS='-Wall')
env.PrependUnique(CPPPATH='#/')

# Define lists for storing library source and include files.
env['lib_includes'] = []
env['lib_sources'] = []

# Subsidiary SConscripts -----------------------------------------------------

Export('env')

# This SConscript updates lib_includes and lib_sources.
SConscript('diffpy/SConscript')

# Define any targets related to testing.
SConscript('tests/SConscript')

# Top Level Targets ----------------------------------------------------------

# lib -- shared library object
libsrreal = env.SharedLibrary('libsrreal', env['lib_sources'])
Alias('lib', libsrreal)

# Installation targets.

prefix = env['prefix']

# install-lib
libdir = env.get('libdir', os.path.join(prefix, 'lib'))
Alias('install-lib', Install(libdir, libsrreal))

# install-includes
includedir = env.get('includedir', os.path.join(env['prefix'], 'include'))
get_target_path = lambda f : os.path.join(includedir, f.path)
include_targets = map(get_target_path, env['lib_includes'])

Alias('install-include', InstallAs(include_targets, env['lib_includes']))

# install
Alias('install', ['install-include', 'install-lib'])

# vim: ft=python
