name: Release (GitHub/PyPI) and Deploy Docs

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  check-tag-privilege:
    uses: scikit-package/release-scripts/.github/workflows/_check-tag-privilege.yml@v0
    with:
      maintainer_github_username: sbillinge

  check-pat-token:
    uses: scikit-package/release-scripts/.github/workflows/_check-pat-token-validity.yml@v0
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  check-pypi-token:
    uses: scikit-package/release-scripts/.github/workflows/_check-pypi-token-validity.yml@v0
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  build:
    needs: [check-tag-privilege, check-pat-token, check-pypi-token]
    uses: ./.github/workflows/_build-and-test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release-github:
    needs: build
    uses: scikit-package/release-scripts/.github/workflows/_release-github.yml@v0
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release-pypi:
    needs: release-github
    uses: scikit-package/release-scripts/.github/workflows/_release-pypi.yml@v0
    with:
      python_version: 3.14
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  docs:
    needs: release-github
    uses: ./.github/workflows/publish-docs-on-release.yml
