name: CI

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  matrix-coverage:
    uses: Billingegroup/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@v0
    with:
      project: diffpy.srreal
      c_extension: true
      headless: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
