name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  matrix-coverage:
    uses: scikit-package/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@v0
    with:
      project: diffpy.srreal
      c_extension: true
      submodules: recursive
      headless: false
      run: |
        set -e
        if [[ $(uname -s) == Linux ]]; then
          python -m pip install git+https://github.com/diffpy/pyobjcryst.git@nanobind_migration_test
          python -c 'import pyobjcryst._pyobjcryst'
        fi
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
