name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  matrix-coverage:
    uses: ./.github/workflows/_build-and-test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
