name: Deploy Documentation on Release

on:
  workflow_dispatch:

jobs:
  docs:
    uses: scikit-package/release-scripts/.github/workflows/_release-docs.yml@v0
    with:
      project: diffpy.srreal
      c_extension: true
      python_version: 0
      headless: false
