name: Tests on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests-on-pr:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr.yml@v0
    with:
      project: diffpy.srreal
      c_extension: true
      headless: false
      run: |
        set -e
        if [[ $(uname -s) == Linux ]]; then
          python -m pip install git+https://github.com/diffpy/pyobjcryst.git@nanobind_migration_test
          python -c 'import pyobjcryst._pyobjcryst'
        fi
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
